# 1 dimenziós CNN PyTorch segítségével
[PyTorch 1D CNN dokumentáció](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html#torch.nn.Conv1d)

Importáljuk a legfontosabb könyvtárakat.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

Elkészítjük a bemeneti adatok (1 dimenziós jel). Ez lesz a feature_vector.

In [ ]:
feature_vector = torch.tensor([3, 4, 3, 2, 1, 0, -1], dtype = torch.float)
print(feature_vector.shape)

torch.Size([7])
torch.Size([1, 1, 7])


Ezután tensor alakba kell hozni, vagyis 3 dimenziós alakba, az unsqueeze metódussal a 0. helyre új dimenziót szúrunk be.

In [ ]:
feature_vector = feature_vector.unsqueeze(0).unsqueeze(0)
print(feature_vector.shape)

Ezután létrehozunk a Conv1d utasítással egy konvolúciós neurális hálót, ami 1 dimenziós jelet vár, 1 dimenzióra transzformál és 3 a filter mérete. Ezeket a filtereket kitöltjük konstans 1 értékkel.

In [ ]:
cnn_model = nn.Conv1d(1, 1, 3)
nn.init.constant_(cnn_model.weight, 1.)
output = cnn_model(feature_vector)

In [ ]:
print(cnn_model.weight)

Parameter containing:
tensor([[[1., 1., 1.]]], requires_grad=True)


In [ ]:
filter = torch.tensor([[2., 5., -3]])

In [ ]:
print(filter.shape)

torch.Size([1, 3])


Itt megnéztük a view függvényt, ami hasonló az unsqueeze-hez, csak itt meg lehet adni a méretét a leendő tenzornak expliciten. (~reshape)

In [ ]:
filter = filter.view(1, 1, 3)

In [ ]:
print(filter)

tensor([[[ 2.,  5., -3.]]])


Ezután amit létrehoztunk filter fogjuk alkalmazni a bemeneten. Itt adhatóak meg a különböző konvolúciós hálónál értelmezett paraméterek (padding, stride, dilation).

In [ ]:
feature_map = F.conv1d(feature_vector, filter, padding = 1)

In [ ]:
print(feature_map)

tensor([[[-44., -11.,  11.,  27.,  20.,   7.,  -5.]]])


Ezután alkalmazünk egy relut a konvolúciós kimeneten.

In [ ]:
feature_map = F.relu(feature_map)

In [ ]:
print(feature_map)

tensor([[[ 0.,  0., 11., 27., 20.,  7.,  0.]]])


Majd egy max poolingot és egy average poolingot.

In [ ]:
feature_map2 = F.max_pool1d(feature_map, kernel_size=2)

In [ ]:
feature_map2 = F.avg_pool1d(feature_map, kernel_size = 2)

In [ ]:
print(feature_map2)

tensor([[[ 0.0000, 19.0000, 13.5000]]])
